version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"
    networks:
      - app-network

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - app-network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - app-network

  rss-producer:
    build: ./rss-producer
    depends_on:
      - kafka
    ports:
      - "8081:8081"
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      RSS_POLLING_INTERVAL_MS: 300000
    networks:
      - app-network

  news-consumer:
    build: ./news-consumer
    depends_on:
      - kafka
      - redis
    ports:
      - "8082:8082"
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      SPRING_REDIS_HOST: redis
    networks:
      - app-network

  news-api:
    build: ./news-api
    ports:
      - "8080:8080"
    depends_on:
      - news-consumer
      - redis
    environment:
      SPRING_REDIS_HOST: redis
    networks:
      - app-network

  news-ui:
    build: ./news-ui
#    ports:
#      - "3000:8083"
    depends_on:
      - news-api
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8083:8083"  # Public access point
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./news-ui/build:/usr/share/nginx/html
    depends_on:
      - news-ui
      - news-api
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

